### ISSUE TITLE
Processing for sketchnet_init.caffemodel

### ISSUE THREAD

**Issue by Ben-Louis** [seuliufeng/DeepSBIR#5]
Hi, thanks for your code and trained models. 
May I ask how did you train sketchnet_init.caffemodel? Did it be pretrained on ImageNet or TU-Berlin?

**Comment by yuqian1023** [comment]
The sketchnet_init.caffemodel is the trained model after conducting step3 (pretraining the triplet models on 187 categories, further details can be found in the paper 'Sketch Me That Shoe'). The single branch has been pretrained on ImageNet and TU-Berlin. Hope this is clarified.

**Comment by Ben-Louis** [comment]
Got it. Thanks for your reply!
